---
  - name: clickhouse-role
    src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
  - name: role_vector
    src: git@github.com:loveyourvoice/role_vector.git
    scm: git
    version: "0.1.0"
  - name: role_lighthouse
    src: git@github.com:loveyourvoice/role_lighthouse.git
    scm: git
    version: "0.1.0"