---
# handlers file for vector-role
# handlers для старта/рестарта сервиса Vector
- name: restart vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
    daemon_reload: true
  when: ansible_facts.virtualization_type != "docker"