---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
    - name: Check vector config
      ansible.builtin.assert:
        that: 
          shell: vector validate --no-environment --config-yaml /etc/vector/vector.yaml     
