---
# tasks file for vector-role
- name: Vector| Install package
  ansible.builtin.include_tasks:
    file: install_{{ ansible_facts.pkg_mgr }}.yml 
# Создание файла конфигурации для vector.
- name: Deploy config Vector
  ansible.builtin.template:
    src: vector.j2
    dest: "{{ vector_config_path }}"
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  become: true
# Создание каталога для sources local_logs
- name: Creates directory
  become: true
  file:
    path: /var/lib/vector/local_logs
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
- name: Create systemd unit Vector
  become: true
  template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
